sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - chromium-browser
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

install:
  - "npm install"

env:
  - CHROME_BIN=/usr/bin/chromium-browser COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=sj8SOxUBGaVeFGSY9ryrC2eTFpVjCPHJl

env:
  - CHROME_BIN=/usr/bin/chromium-browser COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=sj8SOxUBGaVeFGSY9ryrC2eTFpVjCPHJl

script: npm test

notifications:
  email:
    - videos5@corp.globo.com
  slack: globo:F1iVlyrzR4iX8OS7h8fwMcqx
